### ISSUE TITLE
Figure layout

### ISSUE THREAD

**Issue by jo-mueller** [dstansby/napari-matplotlib#22] opened 2022-05-03 14:59 UTC
Hey @dstansby ,

do you think it would be possible to make the axes layout (background color, spine color, x/y_label color) a bit more conformal with Napari (i.e. use the same color scheme)? 

I saw that some of these parameters (e.g. colors) are set in the actual plot commands - maybe this could be put in the place where the plot widget is initially defined. 

Let me know what you think - I may already have some code at hand to do this :)

**Comment by dstansby** [comment] 2022-05-03 15:20
I think this is a duplicate of https://github.com/dstansby/napari-matplotlib/issues/1?

**Comment by dstansby** [comment] 2022-05-03 15:21
Woops, didn't mean to close, but do let me know here if this is different to #1 and I can re-open this issue.

**Closed by dstansby** 2022-05-03 15:20 UTC

**Comment by jo-mueller** [comment] 2022-05-04 07:21
Not really, thanks for pointing it out!
